### ISSUE TITLE
If the job is already deleted by ttl

### ISSUE THREAD

**Issue by klamas1** [groundnuty/k8s-wait-for#50]
We got a problem.
We use k8s-wait-for in initContainers in the workload to wait for database migrations to complete, and we have HPA running.
If the ttlSecondsAfterFinished on the Job expires and the pod is removed, then the new workload pods fail the job check.

What options do we have to solve the problem?

**Comment by groundnuty** [comment]
could you provide some 'snapshots' of 'kubectl get pods' of moments like
- all is still ok, and waiting
- ttlSecondsAfterFinished, expired
- `new workload pods fail the job check`

so I can better understand your usecase?

**Comment by klamas1** [comment]
Run release
```
$ k get po -n web-qc
NAME                                                READY   STATUS     RESTARTS   AGE
arm-qc-green-666554fdd6-6mkpb                       0/1     Init:0/1   0          22s
arm-qc-green-migrations-2022-05-29-19-27-28-2mpdg   1/1     Running    0          22s
```

Job completed and pod up
```
$ k get po -n web-qc
NAME                                                READY   STATUS      RESTARTS   AGE
arm-qc-green-666554fdd6-6mkpb                       1/1     Running     0          77s
arm-qc-green-migrations-2022-05-29-19-27-28-2mpdg   0/1     Completed   0          77s
```

Job has been deleted after ttlSecondsAfterFinished: 180
```
$ k get job -n web-qc
No resources found in web-qc namespace.
```

Doing a scale deployment
```
$ k get po -n web-qc
NAME                               READY   STATUS                  RESTARTS   AGE
arm-qc-green-666554fdd6-6mkpb      1/1     Running                 0          4m14s
arm-qc-green-666554fdd6-997wr      0/1     Init:Error   1          13s
```

New pods crash with an init error 
```
$ k logs -n web-qc pod/arm-qc-green-666554fdd6-997wr -c arm-wait-migrations
Error from server (NotFound): jobs.batch "arm-qc-green-migrations-2022-05-29-19-27-28" not found
```

**Comment by groundnuty** [comment]
That's actually a very practical usecase!

Atm. the behaviour is quite correct. It does not find a pod that it should be waiting for so it informatively fails stating that something isn't right with the deployment (alternatively it could wait for the pod to start, but that may never happen if something actually went wrong).

We could add a similar functionality that was introduced in [Errors can be good](https://github.com/groundnuty/k8s-wait-for/releases/tag/v1.2) release, but with respect to missings. Something like `job-wm` as in `with-missing` that takes an optional argument of time  (default would be 0s) it should expect the pod to appear before assuming that it will never appear and that's ok.

A more elaborate solution would be, to check if there are replicas of 'arm-qc-green-666554fdd6-6mkpb' in Running state (what means that a the same waiting condition did succeed in the past), but it would not work when running 'k rollout restart  statefullset/deployment arm-qc-green' as all the pods would restart and fail since the job no longer exists. 

I think (correct me if I'm wrong) there is no place to remember/get information about the fact that job used to be there - it just Completed and got cleaned.

**Comment by klamas1** [comment]
Yes, there is no information about the completed task anywhere, except to perform another check, through the application, that the migrations were completed, but this would further complicate the scheme

Yes, I thought it over again and it looks like this problem is not the concern of this service.
The solution is to remove the `ttlSecondsAfterFinished` option from the Job. Thus Job will not be deleted "never".
In this case, it is better to set `restartPolicy: OnFailure` so that the Job does not create many pods when it fails, but restarts the same container.

Moreover, if we create a Job with different names for each release,
I create like this: `name: {{ printf "%s-migrations-%s" (include "arm.fullname" .) (now | date "2006-01-02-15-04-05") }}`, then helm successfully removes the old Job and its pods. This is the right behavior.

**Comment by EraYaN** [comment]
> We could add a similar functionality that was introduced in [Errors can be good](https://github.com/groundnuty/k8s-wait-for/releases/tag/v1.2) release, but with respect to missings. Something like `job-wm` as in `with-missing` that takes an optional argument of time (default would be 0s) it should expect the pod to appear before assuming that it will never appear and that's ok.

This would still be very handy for us, since we are not using Helm for deployment (and so old jobs are not cleaned up. But a rescheduled pod won't be able to start when it's DB migration job is missing.

So something so that we could do:

```bash
wait_for.sh job-wm service-db-migration-job-release-YYYYMMDD.N 10
```
Or the other way around of course, so it would wait 10 seconds to see if the job would exist, if it does it waits for Success if it does not it passes since this is likely some restart much later down the line (far beyond the job ttl).

**Comment by groundnuty** [comment]
@EraYaN Maybe oneliner like this (added new lines so it fits in the comment):

```bash
(  \
kubectl wait --timeout=1s --for=condition=Initialized pod -l job-name=service-db-migration-job-release-YYYYMMDD.N \
&& \
wait_for.sh job-wm service-db-migration-job-release-YYYYMMDD.N \
)  \
|| \
(  \
sleep 10 \
&& \
wait_for.sh job-wm service-db-migration-job-release-YYYYMMDD.N \
)

```
If the job exists (let us assume that exists means that the pod is Initialized), then wait for it to finish.
If it does not exist, then wait 10 seconds and try waiting for it. If waiting fails, then it still does not exist and you can handle it.

**Comment by klamas1** [comment]
Maybe this is not solved by skipping a non-existent pod, so you can get !(false positive), but to add to the doc that if we use a job in helm with hooks we should NOT use spec.ttlSecondsAfterFinished ?
(and describe a case in which non-compliance with this rule will definitely shoot a in the leg)

Tolerating the negative result of the existence of a checked migration job may not work correctly in some corner cases. For example, if all nodes are under resource pressure. The cluster is already unhealthy and we will still start the pods that are not healthy

**Comment by EraYaN** [comment]
We have already worked around this limitation with ttlSecondsAfterFinished by just scripting our way out of it during deployment. We add the dependent job name as a label and just run an extra script to clear out any jobs left over from older deployments (minus last three to support deployment rollbacks). So essentially you delete all jobs that no longer have any running deployments and aren't the 3 newest.

**Comment by LukeAbell** [comment]
@EraYaN any chance you could provide an example of the script you're running to clear older deployments?

**Comment by EraYaN** [comment]
We use this bash function: (first argument is your service name or app label value).
```bash
function clean_jobs {
    echo "Getting jobs still in use..."
    
    kubectl get pods -lapp=$1 -ldepends-on-job -o 'jsonpath={range .items[*]}{.metadata.labels.depends-on-job}{"\n"}{end}' | tee $WORK_DIR/in-use-jobs.txt
    echo "Getting all jobs..."
    kubectl get jobs -lapp=$1 --sort-by=.metadata.creationTimestamp -o 'jsonpath={range .items[*]}{.metadata.name}{"\n"}{end}' | tee $WORK_DIR/all-jobs.txt

    echo "Getting filtered jobs and removing..."
    cat $WORK_DIR/all-jobs.txt | grep --invert-match -f $WORK_DIR/in-use-jobs.txt | head -n -2 | xargs -I {} kubectl delete job {}
}
```

and in our helm deployment we add:
```yaml
depends-on-job: "{{ include "service.fullname" . }}-db-migration-{{ .Values.buildName }}"
```
as a pod template label
